---
title: "Generate PowerPoint for Bev VMI"
output: html_document
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## R Markdown

```{r Load Packages and Read Raw Data}
library(xts)
library(gridExtra)
#library(plyr)
library(broman)
library(ReporteRs)

# Set options for ReporteRs
options("ReporteRs-default-font" = "Veranda",
        "ReporteRs-fontsize" = 12)

if (!exists("proj_root")) proj_root <- 
    file.path("~", "Projects", "SUS Roll Consolidation") 

if (!exists("basepath")) basepath <- 
  file.path("~","Projects", "RollAssortmentOptimization")

if (!exists("projscenario")) projscenario <- "VMI-98-8-150-500v3"
if (!exists("mYear")) mYear <- "2016"

# Load Packages & Functions
source(file.path(basepath, "R", "0.LoadFunctions.R"))

source(file.path(proj_root, "R", "FuncReadResults.R"))

```

```{r Read Data}

# Make sure we have the post processed opt_detail
if (!exists("opt_detail")) {
  source(file.path(proj_root, "R", "7.1 Opt Solution Post Process.R"))
}

#Summarize SKU counts by product type
if (!exists("rd_comb")) source(file.path(proj_root, "R", 
                                         "YoY Data Comp.R"))

sku_summary <- rd_comb %>%
  filter(Year == "2016" & (Bev.VMI | CPD.VMI)) %>%
  rename(`Prod Type` = Prod.Type) %>%
  mutate(`Prod Type` = sub("\\.", " ", `Prod Type`)) %>%
  #group_by(`Prod Type`) %>%
  summarize(`2016 Tons` = round(sum(Tons), 0),
            `SKU Count` = n(),
            `Die Count` = sum(Nbr.Dies, na.rm = TRUE),
            `2016 Tons Common to 2015` = 
              round(sum(ifelse(Common.SKU, Tons, 0), na.rm = TRUE), 0),
            `2016 SKUs Common to 2015` = 
              n_distinct(ifelse(Common.SKU, Tons, 0)))

#sku_totals <- sku_summary %>%
#  summarize(`2016 Tons` = sum(`2016 Tons`),
#            `SKU Count` = sum(`SKU Count`),
#            `Die Count` = sum(`Die Count`),
#            `2016 Tons Common to 2015` = sum(`2016 Tons Common to 2015`),
#            `2016 SKUs Common to 2015` = sum(`2016 SKUs Common to 2015`)) %>%
#  mutate(`Prod Type` = "Total")
#
#sku_summary <- bind_rows(sku_summary, sku_totals)

```


```{r Slide 1 Raw Data Summary}
#my_header_cell_props <- cellProperties(border.color = "white",
#                                       background.color = "#81BC41",
#                                       border.bottom.width = 2)
my_f_table <- 
  FlexTable(data = 
              mutate(sku_summary,
                     `2016 Tons` = comma(`2016 Tons`),
                     `SKU Count` = comma(`SKU Count`),
                     `Die Count` = comma(`Die Count`),
                     `2016 Tons Common to 2015` = 
                       comma(`2016 Tons Common to 2015`),
                     `2016 SKUs Common to 2015` = 
                       comma(`2016 SKUs Common to 2015`)),
            header.cell.props = 
              cellProperties(vertical.align = "middle",
                             background.color = "#81BC41",
                             border.color = "white",
                             border.bottom.width = 2,
                             padding = 5),
            header.par.props = parProperties(text.align = "center"),
            header.text.props = textProperties(font.family = "Veranda",
                                               color = "white",
                                               font.weight = "bold"),
            body.cell.props = 
              cellProperties(padding = 5,
                             vertical.align = "middle",
                             border.color = "white"),
            body.text.props = textProperties(font.family = "Veranda",
                                             color = "#6D6E71"),
            body.par.props = parProperties(text.align = "right"))

my_f_table <- setZebraStyle(my_f_table, odd = "#D8E7CF", even = "#EDF4E8")
# Format the footer row
my_f_table[nrow(sku_summary), ] <- textProperties(font.family = "Veranda",
                                                  font.weight = "bold",
                                                  color = "#6D6E71")
# Left justify the first column
#my_f_table[, 1] <- parProperties(text.align = "left")
#my_f_table[1, 1] <- "Some Long Lines of Text"
my_f_table <- setFlexTableWidths(my_f_table, 
                                 widths = c(rep(0.8, 3), rep(1, 2)))
print(my_f_table)

tons_by_width <- ggplot(mutate(opt_detail, GCDW = paste(Grade, CalDW)),
       aes(x = Prod.Width, y = Prod.DMD.Tons)) +
  geom_bar(stat = "identity", width = .25, position = "stack", 
           aes(fill = Grade)) +
  ggtitle("2016 SUS SKU Volume by Width") +
  scale_y_continuous(name = "Tons", 
                     labels = unit_format(unit = "K", scale = 1/1000)) +
  scale_x_continuous(name = "Product Width")

tons_by_width

pareto_df <- opt_detail %>%
  select(Fac, Grade, CalDW, Prod.Width, Prod.DMD.Tons, Prod.Type) %>%
  arrange(desc(Prod.DMD.Tons)) %>%
  mutate(SKU.Nbr = row_number()) %>%
  mutate(Tons = cumsum(Prod.DMD.Tons)) %>%
  mutate(x = lag(SKU.Nbr, default = 0), y = lag(Tons, default = 0), 
         xend = SKU.Nbr, yend = Tons,
         Cum.Pct = Tons/sum(Prod.DMD.Tons))

idx <- which.max(pareto_df$Cum.Pct > .8)
x_end <- pareto_df$xend[idx]
y_end <- pareto_df$yend[idx]

pareto <- ggplot(data = pareto_df, aes(x = SKU.Nbr, y = Tons)) +
  geom_segment(aes(x = x, xend = xend, y = y, yend = yend,
                   #color = Prod.Type), size = 1.5, alpha = 0.7) +
                   color = Grade), size = 1.5) +
  scale_y_continuous(labels = unit_format(unit = "K", scale = 1/1000)) +
  scale_x_continuous(name = "SKU Ranking") +
  geom_segment(aes(x = 0, xend = x_end, y = y_end, yend = y_end),
               color = "black", size = 1) +
  geom_segment(aes(x = x_end, xend = x_end, y = 0, yend = y_end),
               color = "black", size = 1) +
  geom_text(label = paste0("80% = ", comma(round(y_end/1000, 0)), 
                           " K Tons"), aes(x = 0, y = y_end),
            vjust = -1, hjust = "inward") +
  geom_text(label = x_end, aes(x = x_end, y = 0),vjust = "inward", 
            hjust = -.5) +
  ggtitle("SKU Volume Pareto")

pareto

# Plot the total volume by facility/machine (and Grade)
fac_total <- opt_detail %>%
  group_by(Fac) %>%
  summarize(Fac.Tons = sum(Prod.DMD.Tons))

by_mach <- ggplot(opt_detail, aes(x = Fac, y = Prod.DMD.Tons)) +
  geom_bar(stat = "identity", aes(fill = Grade)) +
  ggtitle("2016 VMI Shipments by Machine") +
  scale_y_continuous(name = "Tons", 
                     labels = unit_format(unit = "K", scale = 1/1000),
                     limits = c(0, 400000)) +
  scale_x_discrete(name = "Mill/Machine") +
  geom_text(data = fac_total, vjust = -.5,
            aes(x = Fac, y = Fac.Tons,
                label = comma(round(Fac.Tons, 0))), position = "stack")
by_mach
rm(fac_total)

mydoc <- pptx(template = 'C:/Users/SchroedR/My Documents/GPI Presentations/GPI 2016 Standard PPT Template - Blank.pptx')

#slide.layouts(mydoc)
#slide.layouts(mydoc, "Custom Layout")

mydoc <- addSlide(mydoc, slide.layout = "Title Slide")
mydoc <- addTitle(mydoc, "SUS Beverage Roll Consolidation", level = 1)
#mydoc <- addTitle(mydoc, "19 April 2017", level = 2)
mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0(mYear, " SUS Beverage 2016 Shipment Data Summary"))
addFlexTable(mydoc, flextable = my_f_table, offx = 0.4, offy = 1.35, 
             width = 5, height = 3.5)
#mydoc <- addParagraph(mydoc, value = pot("This is some text"),
#                      par.properties = parProperties(text.align="center", padding=0),
#                      offx = 0.75, offy = 1, width = 2, height = 3)
mydoc <- addPlot(mydoc, fun = function() print(by_mach),
                 offx = .1, offy = 3, width = 5, height = 4)
mydoc <- addPlot(mydoc, fun = function() print(tons_by_width), 
                 offx = 5, offy = 1.25, width = 5, height = 2.8)
mydoc <- addPlot(mydoc, fun = function() print(pareto), 
                 offx = 5, offy = 4.1, width = 5, height = 2.8)

#mydoc <- addPageNumber(mydoc)
ppt_file <- file.path(proj_root, paste0("model-results-", projscenario,".pptx"))
writeDoc (mydoc, ppt_file)
rm(tons_by_width, pareto, my_f_table)
rm(pareto_df, x_end, y_end, by_mach)

```
```{r Slide 2 W6 Consolidation Graphic}

opt_detail %>%
  group_by(Fac) %>%
  summarize(Nbr.Products = n(),
            Nbr.Parents = n_distinct(Fac, Grade, CalDW, Parent.Width))

w6_res <- opt_detail %>%
  group_by(Fac) %>%
  filter(Fac == "W6") %>%
  summarize(Nbr.Products = n(),
            Nbr.Parents = n_distinct(Fac, Grade, CalDW, Parent.Width))


# Consolidation for all of W6
w6_plot <- ggplot(filter(opt_detail_plot, Fac == "W6"), 
       aes(x = Width, y = Tons, fill = Type, 
           width = Bar.Width)) +
  geom_bar(stat = "identity", 
           position = "identity",
           alpha = 0.5) +
  scale_fill_manual(values = c("red", "blue")) +
  scale_y_continuous(labels = comma) +
  coord_flip() +
  geom_text(data = filter(opt_detail_plot, Fac == "W6" & 
                            Type == "Parent.DMD"),
            aes(label = Width), size = 1.5,
            hjust = "inward") +
  facet_grid(Grade ~ CalDW, scales = "free_x") +
  ggtitle(paste0("West Monroe #6 Consolidation")) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1.0),
        text = element_text(size = 7),
        legend.key.size = unit(1, "strheight", "1"))

w6_plot

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("The Optimization Model for WM #6",
                                " Suggest consolidating from ",
                                w6_res$Nbr.Products, " rolls down to ",
                                w6_res$Nbr.Parents))
mydoc <- addPlot(mydoc, fun = function() print(w6_plot),
                 offx = .45, offy = 1.35, width = 9, height = 5.5)

writeDoc (mydoc, ppt_file)

rm(w6_plot, w6_res)

```
```{r Slide 3 W6 AKPG Consolidation Graphic}

w6_akpg_res <- opt_detail %>%
  group_by(Fac, Grade) %>%
  filter(Fac == "W6" & Grade == "AKPG") %>%
  summarize(Nbr.Products = n(),
            Nbr.Parents = n_distinct(Fac, Grade, CalDW, Parent.Width))


# Consolidation for all of W6 AKPG
w6_akpg_plot <- ggplot(data = filter(opt_detail_plot, Fac == "W6" &
                           Grade == "AKPG"), 
       aes(x = Width, y = Tons, fill = Type, 
           width = Bar.Width)) +
  geom_bar(stat = "identity", 
           position = "identity",
           alpha = 0.5) +
  scale_fill_manual(values = c("red", "blue")) +
  scale_y_continuous(labels = comma) +
  coord_flip() +
  geom_text(data = filter(opt_detail_plot, Fac == "W6" & 
                            Grade == "AKPG" &
                            Type == "Parent.DMD"),
            aes(label = Width), size = 1.5,
            hjust = "inward") +
  facet_grid(Grade ~ CalDW, scales = "free_x") +
  ggtitle(paste0("West Monroe #6 AKPG Consolidation")) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1.0),
        text = element_text(size = 7),
        legend.key.size = unit(1, "strheight", "1"))

w6_akpg_plot

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("The Optimization Model for AKPG on WM #6",
                                " Suggest consolidating from ",
                                w6_akpg_res$Nbr.Products, " rolls down to ",
                                w6_akpg_res$Nbr.Parents))
mydoc <- addPlot(mydoc, fun = function() print(w6_akpg_plot),
                 offx = .45, offy = 1.35, width = 9, height = 5.5)

writeDoc (mydoc, ppt_file)

rm(w6_akpg_plot, w6_akpg_res)

```


```{r Slide 4 Model Summary and Sim Plots}

# Fill a table with solution options

# Sim base is sim_parents filtered for 1 roll per parent (no consolidation)
all_prods <- sim_base %>% 
  summarize(Sub.Rolls = n(),
            Nbr.Rolls = n(),
            Annual.Tons = round(sum(Sim.Parent.DMD), 0),
            Avg.OH = round(sum(Sim.Parent.Avg.OH), 0),
            Total.DOH = round(365*sum(Sim.Parent.Avg.OH)/sum(Sim.Parent.DMD), 1),
            Trim.Tons = 0,
            Fill.Rate = round(sum(Sim.Parent.DMD * Sim.Parent.Qty.Fill.Rate, 
                                  na.rm = T)/
              sum(Sim.Parent.DMD), 3)) %>%
  mutate(Title = "Stock all SKUs (no consolidation)")

# Max consolidation - read the All Solution Details and select the rows with 
#  the minimum of the SolParentCount column for each FAC
min_parents <- read_results("all_details", mYear, projscenario)
min_parents <- min_parents %>%
  group_by(Fac) %>%
  filter(SolParentCount == min(SolParentCount)) %>%
  ungroup() %>%
  mutate(nbr_prods = n())

min_parents <- min_parents %>%
  distinct(Grade, CalDW, Parent.Width, Parent.Trim.Tons, 
           Parent.Exp.OH.Tons, Sim.Parent.DMD,
           Sim.Parent.Avg.OH, Sim.Parent.Qty.Fill.Rate, nbr_prods)

min_parents <- min_parents %>%
    summarize(Sub.Rolls = max(nbr_prods),
            Nbr.Rolls = n(),
            Annual.Tons = round(sum(Sim.Parent.DMD), 0),
            Avg.OH = round(sum(Sim.Parent.Avg.OH), 0),
            Total.DOH = round(365*sum(Sim.Parent.Avg.OH)/sum(Sim.Parent.DMD), 1),
            Trim.Tons = round(sum(Parent.Trim.Tons), 0),
            Fill.Rate = round(sum(Sim.Parent.DMD * Sim.Parent.Qty.Fill.Rate, 
                                  na.rm = T)/
              sum(Sim.Parent.DMD), 3)) %>%
  mutate(Title = "Max Consolidation")


group_by(sim_parents, Fac, Grade, CalDW) %>%
  summarize(max(nbr_rolls))

# Optimum solution
all_parents <- opt_parents %>% 
    summarize(Sub.Rolls = sum(Parent.Nbr.Subs),
            Nbr.Rolls = n(),
            Annual.Tons = round(sum(Parent.DMD), 0),
            Avg.OH = round(sum(Sim.Parent.Avg.OH), 0),
            Total.DOH = round(365*sum(Sim.Parent.Avg.OH)/sum(Parent.DMD), 1),
            Trim.Tons = round(sum(Parent.Trim.Loss), 0),
            Fill.Rate = round(sum(Parent.DMD * Sim.Parent.Qty.Fill.Rate)/
              sum(Parent.DMD),3)) %>%
  mutate(Title = "Optimal Consolidation")

options <- bind_rows(all_prods, min_parents, all_parents)

options <- add_row(options)
options$Title[4] <- "Change (vs. Optimal)"
options$Nbr.Rolls[4] <- options$Nbr.Rolls[3] - options$Nbr.Rolls[1]
options$Avg.OH[4] <- options$Avg.OH[3] - options$Avg.OH[1]
options$Trim.Tons[4] <- options$Trim.Tons[3] - options$Trim.Tons[1]

options$Total.DOH[4] <- options$Total.DOH[3] - options$Total.DOH[1]
options$Annual.Tons[4] <- options$Annual.Tons[3] - options$Annual.Tons[1]

oh_tons_dec <- comma(-1 * round(options$Avg.OH[4], -2))
trim_tons_inc <- comma(options$Trim.Tons)

options <- options %>%
  mutate(Scenario = Title,
         `Parent Rolls` = comma(Nbr.Rolls),
         `SKU Count` = comma(Sub.Rolls),
         `Tons Shipped` = comma(Annual.Tons),
         `Avg. OH Tons` = comma(Avg.OH),
         `Avg. DOH` = comma(Total.DOH),
         `Trim Loss Tons` = comma(Trim.Tons),
         `Fill Rate` = percent(Fill.Rate)) %>%
  select(-(1:8))

options[options == "NA" | options == "NA%"] <- ""


f_table2 <- FlexTable(data = options,
                      header.cell.props = 
                        cellProperties(vertical.align = "middle",
                                       background.color = "#81BC41",
                                       border.color = "white",
                                       border.bottom.width = 2,
                                       padding.top = 5,
                                       padding.bottom = 5),
                      header.par.props = 
                        parProperties(text.align = "center"),
                      header.text.props = 
                        textProperties(font.family = "Veranda",
                                       color = "white",
                                       font.weight = "bold"),
                      body.cell.props = 
                        cellProperties(padding.right = 5,
                                       padding.left = 3, padding.top = 5,
                                       padding.bottom = 3,
                                       vertical.align = "middle",
                                       border.color = "white"),
                      body.text.props = textProperties(font.family = "Veranda",
                                                       color = "#6D6E71"),
                      body.par.props = parProperties(text.align = "right"))

f_table2 <- setZebraStyle(f_table2, odd = "#D8E7CF", even = "#EDF4E8")
f_table2 <- setFlexTableWidths(f_table2, widths = c(3, rep(.9, 7)))
f_table2[1:f_table2$numrow, 1] <- parProperties(text.align = "left")

print(f_table2)
mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Model Results & QV Inventory Comparison: ",
                               "Model predicts a ", 
                               oh_tons_dec, " ton inventory ", 
                               "reduction from baseline with",
                               trim_tons_inc, " tons of incremental",
                               "converting trim"))
addFlexTable(mydoc, flextable = f_table2, offx = .3, offy = 1.4, 
             width = 10, height = 6)

# Add the aggregate simulation and QV actual plot from 9. Aggregate Sim Plots.R
if (!exists("t_data_res")) {
  source(file.path(proj_root, "R", "9. Aggregate Sim Plots.R"))
}
sim_qv_plot <- ggplot(data = t_data_res,  
       aes(x = Date)) +
  geom_step(aes(color = Scenario, y = On.Hand, size = Scenario), 
            alpha = .85) +
  scale_y_continuous(name = "On Hand Tons", labels = comma, 
                     limits = c(NA, 50000)) +
  ggtitle("Simulation Results and QlikView Actuals") +
  #scale_color_brewer(palette = "Set1") +
  geom_line(aes(color = Scenario, y = Avg.OH), size = .1) +
  scale_size_manual(values = c(.2, .2, 1.2))
  #geom_label(aes(x = max(Date), y = Avg.OH, label = 
  #                 format(Avg.OH, big.mark = ",")), hjust = "inward") 
  #geom_smooth(aes(y = On.Hand, color = Scenario), se = FALSE,
  #            span = 0.2)

mydoc <- addPlot(mydoc, fun = function() print(sim_qv_plot),
                 offx = .45, offy = 3.2, width = 9, height = 3.7)
print(sim_qv_plot)

writeDoc (mydoc, ppt_file)

#mydoc <- pptx(ppt_file)

# Clean up
rm(all_parents, all_prods, f_table2, my_order, option_list, options,
   sim_qv_plot)

```

```{r Slide 5 Safety Stock Pooling}
# W6 AKPG 24-84-W 36.75 & 37.75
# Fill zeros in the time series and aggregate by week
if (!exists("rawDataAll")) {
  source(file.path(proj_root, "R", "3.Read Data.R"))
}

rtdf <- rawDataAll %>%
  filter(Mill == "W6" & Grade == "AKPG" &
           CalDW == "24-84-W" &
           Width %in% c(36.75, 37.75)) %>%
  group_by(Mill, Grade, CalDW, Width, Date) %>%
  summarize(Tons = round(sum(Tons), 1)) %>%
  ungroup()

# Compute the tons by week
my_fun <- function(x) {
  tdays <- data.frame(seq.Date(as.Date("2016-01-01"), 
                               as.Date("2016-12-31"), by = "day" ))
  colnames(tdays)[1] <- "Date"
  m_mill <- x$Mill[1]
  m_grade <- x$Grade[1]
  m_caldw <- x$CalDW[1]
  x <- left_join(tdays, x, by = c("Date"))
  x <- mutate(x, Tons = ifelse(is.na(Tons), 0, Tons))
  x <- fill(x, Width)
  x <- fill(x, Width, .direction = "up")
  week_end <- endpoints(x$Date, "weeks")
  x_week <- as.data.frame(period.apply(x$Tons, week_end, FUN = sum))
  colnames(x_week)[1] <- "Tons"
  x_week$Week.End <- x$Date[week_end]
  x_week$Mill <- m_mill
  x_week$Grade <- m_grade
  x_week$CalDW <- m_caldw
  return(x_week)
}

#tdf <- ddply(rtdf, "Width", my_fun)
tdf <- rtdf %>% split(.$Width) %>%
  map_df(my_fun, .id = "Width")
tdf$Width <- as.character(tdf$Width)

tdf_comb <- tdf %>%
  group_by(Mill, Grade, CalDW, Week.End) %>%
  summarize(Tons = sum(Tons)) %>%
  mutate(Width = "Combined")

tdf <- bind_rows(tdf, tdf_comb)
rm(tdf_comb)  

tdf <- tdf %>%
  group_by(Width) %>%
  mutate(Fcst = mean(Tons)) %>%
  mutate(Error = Tons - Fcst,
         SD = sd(Tons),
         Scale = sd(Tons)^2/mean(Tons),
         Shape = mean(Tons)^2/sd(Tons)^2) %>%
  ungroup()

tdf_stats <- tdf %>% dplyr::select(Width, Fcst, SD, Scale, Shape) %>%
  distinct() %>%
  mutate(SS98 = SD * qnorm(.98, 0, 1))

tdf_stats_sum <- tdf_stats %>%
  filter(Width %in% c("36.75", "37.75")) %>%
  summarize(Fcst = sum(Fcst), SD = sum(SD), SS98 = sum(SS98)) %>%
  mutate(Width = "Sum")

tdf_stats <- bind_rows(tdf_stats, tdf_stats_sum)
rm(tdf_stats_sum)

gtons <- ggplot(data = tdf, aes(x = Week.End, y = Tons)) +
  geom_bar(stat = "identity", aes(fill = Width)) +
  facet_grid(Width ~ ., switch = "y") +
  ggtitle("Shipment Tons by Week") +
  scale_fill_discrete(guide = FALSE) +
  theme(axis.title.y = element_blank()) +
  xlab("Week Ending Date")


print(gtons)

# Histogram with counts of occurrences
ghist <- ggplot(data = tdf, aes(x = Tons)) + 
  geom_histogram(aes(colour = Width), fill="white", bins = 15) +
  #stat_bin(bins = 15, geom = "line") +
  #stat_density(aes(color = Width), size = 1, position="identity") +
  #stat_count() +
  #stat_function(fun = dgamma, args = fitdistr(tdf$Tons, "gamma")$estimate)
  ggtitle("Shipment Histogram") +
  coord_flip() +
  facet_grid(Width ~ .)
print(ghist)

ghist_nz <- ggplot(filter(tdf, Tons > 0), aes(x = Tons)) + 
  geom_histogram(aes(colour = Width), fill="white", bins = 15) +
  #stat_density(color="green", size = 1, position="identity") +
  #stat_function(fun = dgamma, args = fitdistr(tdf$Tons, "gamma")$estimate)
  ggtitle("Shipment Histogram - Exclude Zero Demands") +
  coord_flip() +
  facet_grid(Width ~ .)
print(ghist_nz)

# Frequency Plot
gfreq = ggplot(data = tdf, aes(x = Tons)) +
  #geom_histogram(aes(color = Width), bins = 15) +
  stat_bin(aes(y = ..density.., color = Width), bins = 25, fill = "white") +
  #geom_density(aes(color = Width), fill = "white", bins = 15) +
  ggtitle("Shipment Frequency by Tons") +
  coord_flip() +
  scale_y_continuous(name = "Frequency", labels = percent) +
  scale_color_discrete(guide = FALSE) +
  facet_grid(Width ~ .)
print(gfreq)

# Bar and Continuous Density Plots.  Note that stat_function cannot be facetted
# so we build our own distribution curve
grid <- with(tdf, seq(min(Tons), max(Tons), length.out = 100))
#normaldens <- plyr::ddply(tdf, "Width", function(df) {
#  data.frame( 
#    Tons = grid,
#    density = dnorm(grid, mean(df$Tons), sd(df$Tons))
#  )
#})
normaldens <- tdf %>% split(.$Width) %>% map_df(function(df) {
  data.frame( 
    Tons = grid,
    density = dnorm(grid, mean(df$Tons), sd(df$Tons))
  )
}, .id = "Width")

#gammadens <- ddply(tdf, "Width", function(df) {
#  data.frame(
#    Tons = grid,
#    density = dgamma(grid, scale = sd(tdf$Tons)^2/mean(tdf$Tons),
#         shape = mean(tdf$Tons)^2/sd(tdf$Tons)^2)
#  )
#})

gammadens <- tdf %>% split(.$Width) %>% map_df(function(df) {
  data.frame(
    Tons = grid,
    density = dgamma(grid, scale = sd(tdf$Tons)^2/mean(tdf$Tons),
         shape = mean(tdf$Tons)^2/sd(tdf$Tons)^2)
  )
}, .id = "Width")
gdens <- ggplot(data = tdf, aes(x = Tons)) + 
  geom_histogram(aes(y = ..density.., color = Width), fill = "white", bins = 25) +
  #geom_density(aes(color = Width)) +
  #geom_density(color="green", size = 1, position="identity") +
  #stat_function(fun = dnorm, args = c(mean = mean(tdf$Tons), 
  #                                    sd = sd(tdf$Tons)),
  #              aes(color = Width), size = 1.) +
  geom_line(aes(y = density, color = Width), data = normaldens) +
  #geom_line(aes(y = density, color = Width), data = gammadens) +
  #stat_function(fun = dgamma, args = c(scale = sd(tdf$Tons)^2/mean(tdf$Tons),
  #       shape = mean(tdf$Tons)^2/sd(tdf$Tons)^2), size = 0.75, aes(color = Width)) +
  #stat_function(fun = dlnorm, args = c(meanlog = mean(tdf$Tons), 
  #                                    sdlog = sd(tdf$Tons)),
  #              aes(color = Width), size = .75) +
  #stat_function(fun = dgamma, args = fitdistr(tdf$Tons, "gamma")$estimate)
  ggtitle("Shipment Size Density Plot with Normal Distribution Fit") +
  coord_flip() +
  facet_grid(Width ~ .) +
  scale_color_discrete(guide = FALSE) +
  ylab("Density") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(),
        axis.ticks.y = element_blank(), strip.text.y = element_blank())

print(gdens)

gerror <- ggplot(tdf, aes(x = Error)) + 
  geom_histogram(colour="red", fill="white", bins = 20) +
  ggtitle("Forecast Errors") +
  coord_flip() +
  facet_grid(Width ~ .)

gdist <- ggplot(tdf, aes(x = Tons)) +
  geom_rug(data = filter(tdf, Width %in% c("36.75", "37.75")), 
                         aes(color = Width)) +
  stat_function(fun = dnorm,
                args = c(mean = tdf_stats$Fcst[1],
                         sd = tdf_stats$SD[1]),
                size = 1, aes(color = tdf_stats$Width[1])) +
  stat_function(fun = dnorm,
                args = c(mean = tdf_stats$Fcst[2],
                         sd = tdf_stats$SD[2]),
                size = 1, aes(color = tdf_stats$Width[2])) +
  stat_function(fun = dnorm, 
                args = c(mean = sum(tdf_stats$Fcst[1:2]), 
                         sd = sum(tdf_stats$SD[1:2])), 
                size = 1.5, aes(color = "Sum")) +
  stat_function(fun = dnorm,
                args = c(mean = tdf_stats$Fcst[3],
                         sd = tdf_stats$SD[3]),
                size = 1.5, aes(color = tdf_stats$Width[3])) +
  geom_segment(data = tdf_stats, size = 1,
     aes(x = SS98, xend = SS98, y = 0, yend = .01, color = Width)) + 
  geom_text(data = tdf_stats[tdf_stats$Width == "Combined", ],
   aes(label = paste0("Sfty Stk = ", round(SS98, 0)),
   x = SS98, y = .011), nudge_x = 10) +
  geom_text(data = tdf_stats[tdf_stats$Width == "Sum", ],
   aes(label = paste0("Sfty Stk = ", round(SS98, 0)),
   x = SS98, y = .011), nudge_x = 20) +
  scale_y_continuous(name = "Frequency") +
  labs(color = "")

print(gdist)

gplot1 <- grid.arrange(gtons, gdens, nrow = 1)

print(gerror)

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Parent Roll Example: Consolidating the 36.75 ",
                               "and 37.75 in. 24 Point AKPG results in a ",
                               "30% reduction in safety stock inventory"))

mydoc <- addPlot(mydoc, fun = function() print(gtons),
                 offx = .45, offy = 1.2, width = 4.5, height = 3)
mydoc <- addPlot(mydoc, fun = function() print(gdens),
                 offx = 5, offy = 1.2, width = 4.5, height = 3)
mydoc <- addPlot(mydoc, fun = function() print(gdist),
                 offx = .45, offy = 4.2, width = 9, height = 3)

writeDoc (mydoc, ppt_file)

rm(gdens, ghist, gerror, gplot1, gtons, grid, normaldens, gammadens)

```

```{r Slide 8 Parent Elim Summary}

# Use the odp_x data frame from 7.2 Save Excel Validation.R
opt_new <- opt_detail_plants %>%
  filter(Prod.Trim.Width >0) %>%
  select(`Plant` = Plant.Abrev, Grade, Cal = Caliper, Dia, Wind, 
         `Roll Width` = Prod.Width, `Parent Roll Width` = Parent.Width, Mill,
         `Roll Tons` = Tons, `Trim Width` = Prod.Trim.Width, 
         `Trim Tons` = Prod.Trim.Plant.Tons, 
         `Parent Plant Count` = Parent.Plant.Count, 
         `Total Parent Tons` = Parent.DMD) 

opt_new <- opt_new %>% 
  group_by(Mill, Grade, Cal, Dia, Wind, `Roll Width`) %>%
  mutate(Plants = paste0(`Plant`, collapse = ", "),
         `Roll Tons` = sum(`Roll Tons`),
         `Trim Tons` = sum(`Trim Tons`)) %>%
  select(-Plant) %>%
  ungroup() %>%
  distinct()

opt_new <- opt_new %>% 
  select(Grade:`Trim Tons`, Plants, everything()) %>%
  mutate(`Roll Tons` = comma(round(`Roll Tons`, 0)),
         `Trim Tons` = round(`Trim Tons`, 1),
         `Total Parent Tons` = comma(round(`Total Parent Tons`, 0)))

opt_new <- opt_new %>%
  arrange(Grade, Cal, `Roll Width`,Dia, Wind)
  
#copy.table(opt_new)

f_table5 <- FlexTable(data = opt_new,
                      header.cell.props = 
                        cellProperties(vertical.align = "middle",
                                       background.color = "#81BC41",
                                       border.color = "white",
                                       border.bottom.width = 2,
                                       padding.top = 3,
                                       padding.bottom = 3),
                      header.par.props = 
                        parProperties(text.align = "center"),
                      header.text.props = 
                        textProperties(font.family = "Veranda",
                                       color = "white",
                                       font.weight = "bold",
                                       font.size = 10),
                      body.cell.props = 
                        cellProperties(padding.right = 5,
                                       padding.left = 3, padding.top = 2,
                                       padding.bottom = 2,
                                       vertical.align = "middle",
                                       border.color = "white"),
                      body.text.props = textProperties(font.family = "Veranda",
                                                       color = "#6D6E71",
                                                       font.size = 8),
                      body.par.props = parProperties(text.align = "right"))

f_table5 <- setZebraStyle(f_table5, odd = "#D8E7CF", even = "#EDF4E8")
f_table5 <- setFlexTableWidths(f_table5, 
                               widths = c(0.5, rep(0.4, 3), rep(0.7, 2), 
                                          0.4, rep(0.5, 3), 2.0, rep(0.6, 2))) 
f_table5[1:f_table5$numrow, 11] <- parProperties(text.align = "left")
f_table5 <- spanFlexTableRows(f_table5, j = 12:13, 
                              runs = as.character(opt_new$`Total Parent Tons`))

print(f_table5)

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Beverage VMI Roll Consolidations"))
addFlexTable(mydoc, flextable = f_table5, offx = .3, offy = 1.27, 
             width = 9.0, height = 6)

writeDoc (mydoc, ppt_file)

# Clean up
rm(opt_new)
  
```


```{r Slide 6 and 7 Parent SKU List by plant}

# Use the odp_x data frame from 7.2 Save Excel Validation.R
opt_new <- opt_detail_plants %>%
  filter(Prod.Trim.Width > 0) %>%
  select(`Plant Name` = Plant.Name, Mill, Grade, Cal = Caliper, Dia, Wind, 
         `Roll Width` = Prod.Width, `Parent Roll Width` = Parent.Width, 
         `Roll Tons` = Tons, `Trim Width` = Prod.Trim.Width, 
         `Trim Tons` = Prod.Trim.Plant.Tons, 
         `Parent Plant Count` = Parent.Plant.Count, 
         `Total Parent Tons` = Parent.DMD) %>%
  mutate(`Roll Tons` = comma(round(`Roll Tons`, 0)),
         `Trim Tons` = round(`Trim Tons`, 1),
         `Total Parent Tons` = comma(round(`Total Parent Tons`, 0)))

my_plants <- unique(opt_new$`Plant Name`)
my_order1 <- c("WEST MONROE - BEVERAGE", "PERRY", "FORT SMITH / BARLING")
my_order2 <- c("LAWRENCEBURG", "STAUNTON (CARDED GRAPHICS)",
              "ELK GROVE VILLAGE WESTFIELD", "PACIFIC",
              "LUMBERTON", "WAYNE", "MISSISSAUGA, ON")

# Make sure we aren't missing any plants
setdiff(my_plants, c(my_order1, my_order2))

opt_new1 <- opt_new %>% 
  filter(`Plant Name` %in% my_order1)
opt_new2 <- opt_new %>%
  filter(`Plant Name` %in% my_order2)

opt_new1$`Plant Name` <- factor(opt_new1$`Plant Name`, levels = my_order1)
opt_new2$`Plant Name` <- factor(opt_new2$`Plant Name`, levels = my_order2)
opt_new1 <- with(opt_new1, opt_new1[order(`Plant Name`),])
opt_new2 <- with(opt_new2, opt_new2[order(`Plant Name`),])

f_table3 <- FlexTable(data = opt_new1,
                      header.cell.props = 
                        cellProperties(vertical.align = "middle",
                                       background.color = "#81BC41",
                                       border.color = "white",
                                       border.bottom.width = 2,
                                       padding.top = 3,
                                       padding.bottom = 3),
                      header.par.props = 
                        parProperties(text.align = "center"),
                      header.text.props = 
                        textProperties(font.family = "Veranda",
                                       color = "white",
                                       font.weight = "bold",
                                       font.size = 10),
                      body.cell.props = 
                        cellProperties(padding.right = 5,
                                       padding.left = 3, padding.top = 2,
                                       padding.bottom = 2,
                                       vertical.align = "middle",
                                       border.color = "white"),
                      body.text.props = textProperties(font.family = "Veranda",
                                                       color = "#6D6E71",
                                                       font.size = 8),
                      body.par.props = parProperties(text.align = "right"))

f_table3 <- setZebraStyle(f_table3, odd = "#D8E7CF", even = "#EDF4E8")
f_table3 <- setFlexTableWidths(f_table3, 
                               widths = c(2.1, rep(0.5, 5), 
                                          rep(0.7, 2), 0.6, 0.5, 
                                          0.5, 0.6, 0.7))
f_table3[1:f_table3$numrow, 1] <- parProperties(text.align = "left")
f_table3 <- spanFlexTableRows(f_table3, j = 1, 
                              runs = as.character(opt_new1$`Plant Name`))

f_table4 <- FlexTable(data = opt_new2,
                      header.cell.props = 
                        cellProperties(vertical.align = "middle",
                                       background.color = "#81BC41",
                                       border.color = "white",
                                       border.bottom.width = 2,
                                       padding.top = 3,
                                       padding.bottom = 3),
                      header.par.props = 
                        parProperties(text.align = "center"),
                      header.text.props = 
                        textProperties(font.family = "Veranda",
                                       color = "white",
                                       font.weight = "bold",
                                       font.size = 10),
                      body.cell.props = 
                        cellProperties(padding.right = 5,
                                       padding.left = 3, padding.top = 2,
                                       padding.bottom = 2,
                                       vertical.align = "middle",
                                       border.color = "white"),
                      body.text.props = textProperties(font.family = "Veranda",
                                                       color = "#6D6E71",
                                                       font.size = 8),
                      body.par.props = parProperties(text.align = "right"))

f_table4 <- setZebraStyle(f_table4, odd = "#D8E7CF", even = "#EDF4E8")
f_table4 <- setFlexTableWidths(f_table4, 
                               widths = c(2.1, rep(0.5, 5), 
                                          rep(0.7, 2), 0.6, 0.5, 
                                          0.5, 0.6, 0.7))
f_table4[1:f_table4$numrow, 1] <- parProperties(text.align = "left")
f_table4 <- spanFlexTableRows(f_table4, j = 1, runs = as.character(opt_new2$`Plant Name`))

print(f_table3)
print(f_table4)

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Roll Width Changes"))
addFlexTable(mydoc, flextable = f_table3, offx = .3, offy = 1.27, 
             width = 9.0, height = 6)

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Roll Width Changes (cont.)"))
addFlexTable(mydoc, flextable = f_table4, offx = .3, offy = 1.27, 
             width = 9.0, height = 6)

writeDoc (mydoc, ppt_file)

# Clean up
rm(my_plants, my_order1, my_order2, opt_new1, opt_new2)

```

```{r Parent Roll Plots}
# Generate plot of trim width
# First put the trim widths in 1/8 inch increments
g_opt_detail <- opt_detail %>%
  mutate(Prod.Trim.Width = ceiling(Prod.Trim.Width*8)/8)
  
gtrim <- ggplot(data = g_opt_detail,
                aes(x = Prod.Trim.Width)) +
  geom_bar(aes(y = Prod.Trim.Tons, fill = Fac),
                 #binwidth = 0.125, color = "black",
                 position = "stack", stat = "identity",
           width = .1) +
  xlab("Converting Trim Width (in.)") +
  ylab("Trim Loss Tons") +
  scale_x_continuous(limits = c(0, 3))+
  ggtitle("Trim Tons versus Trim Width")

#vtrim <- ggvis(data = g_opt_detail, 
#               x = ~Prod.Trim.Width, 
#               y = ~Prod.Trim.Tons) %>%
#  layer_bars(fill = ~Parent.Policy)

gtrim

mydoc <- addSlide(mydoc, slide.layout = "Custom Layout")
mydoc <- addTitle(mydoc, paste0("Parent Roll Trim Loss is Mostly ",
                               "Less than 2.0 in."))

mydoc <- addPlot(mydoc, fun = function() print(gtrim),
                 offx = .45, offy = 1.2, width = 4.5, height = 3)

writeDoc (mydoc, ppt_file)

rm(gtrim, g_opt_detail)
```


```{r VMI Rolls on the VMI List from Rick}

# Build a summary VMI list to compare back to the original
# This gets messy with all the intermediate tables, but it seems
# to work.  Could probably be done in fewer steps
vmi_rolls <- read.xlsx(file.path(proj_root, "Data", "VMI List.xlsx"),
                       startRow = 2, cols = c(1:6)) %>%
  mutate(Caliper = as.character(Caliper))

vmi_rolls[is.na(vmi_rolls)] <- ""

# Aggregate over Diameter and Wind direction for each Plant & Mill
opt_new <- opt_detail_plants %>%
  select(Mill, Plant.Abrev, Caliper, Grade, Prod.Width, Parent.Width, 
           Prod.Trim.Width, Tons, Prod.Trim.Plant.Tons) %>%
  rename(Trim.Width = Prod.Trim.Width) %>%
  ungroup()

#opt_new %>% summarize(Tons = sum(Tons), Trim.Tons = sum(Prod.Trim.Plant.Tons))

# Build the plant list string
opt_new_c  <- opt_new %>% 
  select(Mill, Plant.Abrev, Caliper, Grade, Prod.Width, Tons)

# Build the facility list string.  First sum without the Mill
opt_new_f <- opt_new_c %>% select(-Mill) %>%
  group_by(Plant.Abrev, Caliper, Grade, Prod.Width) %>%
  summarize(Tons = sum(Tons)) %>%
  ungroup() %>%
  mutate(Plant.Abrev = paste0(Plant.Abrev, 
                              " (", comma(round(Tons, 0)), ")")) %>%
  group_by(Caliper, Grade, Prod.Width) %>%
  mutate(Plants = paste0(Plant.Abrev, collapse = ", ")) %>%
  ungroup()

opt_new_f <- opt_new_f %>%
  select(-Plant.Abrev, -Tons) %>%
  distinct()

# Build the Mill list string
opt_new_m <- opt_new_c %>% select(-Plant.Abrev, -Tons) %>%
  distinct() %>%
  group_by(Caliper, Grade, Prod.Width) %>%
  mutate(Mills = paste0(Mill, collapse = ", "))%>%
  ungroup()

opt_new_m <- opt_new_m %>%
  select(-Mill) %>%
  distinct()

opt_new_c <- full_join(opt_new_m, opt_new_f,
                       by = c("Caliper", "Grade", "Prod.Width"))

opt_new <- opt_new %>%
  group_by(Mill, Caliper, Grade, Prod.Width, Parent.Width, Trim.Width) %>%
  summarize(Tons = sum(Tons),
            Trim.Tons = sum(Prod.Trim.Plant.Tons)) %>%
  ungroup()

opt_new_c <- left_join(opt_new, opt_new_c,
                       by = c("Grade", "Caliper", "Prod.Width"))

opt_new_c %>% summarize(Tons = sum(Tons))

opt_new <- left_join(vmi_rolls, opt_new_c,
                     by = c("Caliper", 
                           "Width" = "Prod.Width", 
                           "Grade"))

opt_new <- opt_new %>%
  filter(!is.na(Tons))

opt_new <- opt_new %>%
  select(Caliper, Width, Grade, Purpose, Die, Status, Mill,
         Tons, Parent.Width, Trim.Width, Trim.Tons, Mills, 
         `Plants (Tons)` = Plants)
  

opt_new %>% summarize(Tons = sum(Tons),
                      Trim.Tons = sum(Trim.Tons))

copy.table(opt_new)


wb <- loadWorkbook(file.path(proj_root, paste0(projscenario, mYear, 
                               "ParentSummary.xlsx")))
if (!("VMI List" %in% names(wb))) {
  addWorksheet(wb, "VMI List")
} else {
  removeWorksheet(wb, "VMI List")
  addWorksheet(wb, "VMI List")
}

writeData(wb, "VMI List", opt_new,
          startCol = 1, startRow = 2,
          withFilter = TRUE)


saveWorkbook(wb, file = file.path(proj_root, paste0(projscenario, mYear, 
                               "ParentSummary.xlsx")), overwrite = TRUE)

rm(opt_new, opt_new_f, opt_new_c, opt_new_m, wb)

```

```{r die info}

# The file comes from QlikView Fiber Analysis Consumption by Die Report, 
# Bookmark = SUS Consumption with the Date set to Month Year.
#
# Try to identify the dies for which the pilot board widths were
# preferred sizes, and not just used as substitutes

cons <- read.xlsx(file.path(proj_root, "Data", 
                           "QV SUS Roll Consumption 2016-2017.xlsx"),
                 detectDates = T)


cons <- cons %>%
  mutate(Plant = paste0("PLT0", Plant),
         Year = as.character(year(MonthYear)),
         Board.Width = as.numeric(Board.Width)) %>%
  filter(Board.Width > 0)

cons <- cons %>%
  filter(MonthYear >= floor_date(start_date, "month") & MonthYear <= end_date)

cons <- cons %>%
  mutate(M.I = str_sub(Material.Description, 1, 1))

# Grade
cons <- cons %>%
  mutate(Grade = ifelse(
        M.I == "I",
        str_sub(Material.Description, 5, 8), # Imperial
        str_sub(Material.Description, 6, 9)  # Metric
        ) 
      )

cons <- cons %>%
  mutate(Wind = str_sub(Material.Description, 
                        str_length(Material.Description), -1))
cons <- cons %>%
  mutate(Dia = ifelse(M.I == "I",
                      str_sub(Material.Description, 19, 20),
                      str_sub(Material.Description, 16, 19)))

# Aggregate over the dates
cons <- cons %>%
  group_by(Plant, PlantName, 
           MRPC2.Text, Die, Die.Description,
           Grade, Board.Caliper, Dia, Wind, Board.Width, M.I,
           Material, Material.Description) %>%
  summarize(Tons = sum(TON)) %>%
  ungroup()

# Calculate the percentage of tons by board width for the dies with 
#   multiple widths.  
cons <- cons %>%
  group_by(Plant, PlantName, Die, Die.Description) %>%
  mutate(Nbr.Widths = n_distinct(Board.Width),
         Tons = round(Tons, 0),
         Die.Tons = round(sum(Tons), 0),
         Die.Pct = round(100*Tons/Die.Tons, 0)) %>%
  ungroup() %>%
  arrange(Plant, Die, desc(Board.Width)) 


# Calculate the percentage of tons by board width for the dies with 
#   multiple widths.  Ignore Grade & Caliper
cons <- cons %>%
  group_by(Plant, PlantName, Die, Die.Description) %>%
  mutate(Nbr.Boards = n_distinct(Board.Width, Grade, Board.Caliper),
         Die.Tons = sum(Tons)) %>%
  mutate(Die.Pct = round(100*Tons/Die.Tons, 2)) %>%
  mutate(Nbr.Subs = sum(ifelse(Die.Pct < 5, 1, 0))) %>%
  ungroup() %>%
  arrange(Plant, Die, desc(Board.Width)) 

# Assume any boards that made up less than 5% of the die tons were
#   un-desired substitutes
cons <- cons %>%
  mutate(Apparent.Sub = ifelse((Die.Pct < 5 & Tons < 50), TRUE, FALSE))

# Just keep the chosen rolls
if (!exists("opt_detail")) opt_detail <- read_results("opt_detail", 
                                                      mYear, projscenario)

cons_pre <- inner_join(cons, select(opt_detail, Fac, Grade, Caliper, Wind, 
                               Prod.Width, Parent.Width),
                  by = c("Grade", "Board.Caliper" = "Caliper", 
                         "Wind", "Board.Width" = "Prod.Width"))

cons_parent <- semi_join(distinct(cons, Grade, Board.Caliper, Wind,
                                Board.Width, Dia, Material, 
                                Material.Description),
                         opt_detail, 
                         by = c("Grade", "Board.Caliper" = "Caliper", 
                         "Wind", "Board.Width" = "Parent.Width"))

cons_parent <- cons_parent %>%
  rename(Parent.Width = Board.Width,
    Parent.Material = Material, 
         Parent.Material.Descr = Material.Description)

cons_final <- left_join(cons_pre, cons_parent,
                        by = c("Grade", "Board.Caliper", "Dia", "Wind",
                               "Parent.Width"))

cons_final <- cons_final %>%
  select(-M.I) %>%
  arrange(Plant, Die, desc(Tons))

cons_final <- cons_final %>%
  filter(Parent.Width != Board.Width)


cons_final <- cons_final %>% 
  select(Board.Caliper, Fac, Grade, Board.Width, Dia, Wind, Plant, 
         `Plant Name` = PlantName, MRPC2.Text, Die,
         Die.Description, 
         Material, Material.Description, Tons, 
         Die.Tons, Die.Pct, Nbr.Boards, Nbr.Subs, Apparent.Sub,
         Parent.Width, Parent.Material, Parent.Material.Descr)

cons_final <- cons_final %>%
  arrange(Board.Caliper, Fac, Grade, Board.Width, Dia, Wind, Plant,
          Die, Tons)

cons_final <- cons_final %>%
  mutate(Die.Pct = percent(`Die.Pct` / 100))

names(cons_final) <- gsub("\\.", " ", names(cons_final))

copy.table(cons_final)

```


```{r BOM Dies}
#
# The BOM data comes from the Board Dies bookmark in the 
# Bill of Materials.qvw cube under the Material Category

bom <- read.xlsx(file.path(proj_root, "Data", 
                           "QV-BOM-dies.xlsx"))

# Fix the plant codes
bom <- bom %>%
  mutate(Plant = paste0("PLT", str_pad(Plant, 5, side = "left", pad = "0")))

# Extract the PMP components from the component desctiption
bom <- bom %>%
  mutate(M.I = str_sub(Component.Description, 1, 1))

bom <- bom %>%
  filter(M.I == "I")

bom <- bom %>% 
  mutate(Roll.Width = ifelse(M.I == "I",
                        str_sub(Component.Description, 10, 17),
                        str_sub(Component.Description, 11, 14)))
bom$Roll.Width <- as.numeric(bom$Roll.Width)

bom <- bom %>%
  mutate(Caliper = ifelse(M.I == "I",
                          str_sub(Component.Description, 3, 4),
                          str_sub(Component.Description, 4, 5)))
bom <- bom %>%
  mutate(Grade = ifelse(M.I == "I",
                        str_sub(Component.Description, 5, 8),
                        str_sub(Component.Description, 6, 9)))

bom <- bom %>%
  mutate(Wind = str_sub(Component.Description, 
                        str_length(Component.Description), -1))

bom <- bom %>%
  mutate(Dia = ifelse(M.I == "I",
                      str_sub(Component.Description, 19, 20),
                      str_sub(Component.Description, 16, 19)))

# Ignore the TRIALs
bom <- bom %>%
  filter(!str_detect(Material.Description, "TRIAL"))

# Make sure we just have one row for each
bom_dist <- bom %>%
  distinct(Plant, Die, Roll.Width, Caliper, Grade, Wind, Dia) %>%
  rename(`BOM Grade` = Grade, `BOM Dia` = Dia, `BOM Wind` = Wind)
  

# Which consumption by die records have a match in the BOM table
# could be multiple
cons_bom <- left_join(cons_final, bom_dist,
                      by = c("Plant", "Die", "Board Caliper" = "Caliper",
                           #   "Grade", "Dia", "Wind", 
                             "Board Width" = "Roll.Width"))



cons_bom[is.na(cons_bom)] <- ""

copy.table(cons_bom)

```
